# Generated by Django 2.2.6 on 2019-11-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20191109_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
