# Generated by Django 2.2.6 on 2019-11-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_document_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='scores',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
