# Generated by Django 2.2.6 on 2019-11-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20191111_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
