# Generated by Django 2.2.6 on 2019-11-27 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20191125_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentassessment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_assessment', to='documents.Document'),
        ),
    ]
