# Generated by Django 2.2.6 on 2019-11-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20191127_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerassessment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_assessments', to='documents.Answer'),
        ),
    ]
